theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
logo: "/assets/images/steg-logo.png"
title: "Steglasaurous"
footer:
  links:
    - label: "Twitch"
      icon: "fab fa-twitch"
      url: "https://twitch.tv/steglasaurous"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/steglasaurous"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCBKI4aVW32RwlhHxDHJBjsw"
